name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TYPST_FILE_NAME: main

    steps:
      - uses: actions/checkout@v4
      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-cjk-extra
      - uses: typst-community/setup-typst@v3
      - run: typst compile ${{ env.TYPST_FILE_NAME }}.typ
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.TYPST_FILE_NAME }}.pdf
          draft: true
          generate_release_notes: true
